version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "nojoke"
    ports:
      - "3306:3306"
    volumes:
      - ./docs/sql/web-sql.sql:/docker-entrypoint-initdb.d/data.sql
      - ./data/mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: ""
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data